name: go-ci-pipeline-test

on: [push, pull_request]

jobs: 
  test:
      strategy:
        matrix:
          go-version: [1.14.x, 1.15.x, 1.16.x]
          platform: [ubuntu-latest, windows-latest]
      runs-on: ${{ matrix.platform }}
      
      steps:
      - uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go-version }}
      - uses: actions/checkout@v2
      - name: Test
        run: go test ./...